In [3]:
import numpy as np

In [5]:
names=np.array([12,34,56])
weights=np.array([34,56,77])

In [7]:
answer=np.dot(names, weights)

In [10]:
np.dot(names, weights)

6624

In [11]:
np.matmul(names, weights)

6624

In [17]:
abc=np.array([[12,45,67],
             [34,67,89],
             [42,56,78],
             [34,56,74]])

cde=np.array([[12,45,67],
             [34,67,89],
             [42,56,78],
             [34,56,74]])
da=np.array([0.1, 0.2,0.4])

In [18]:
np.matmul(abc, da)

array([37. , 52.4, 46.6, 44.2])

In [19]:
abc @ da

array([37. , 52.4, 46.6, 44.2])

In [21]:
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'data.txt')

('data.txt', <http.client.HTTPMessage at 0x7f534864fa20>)

In [26]:
datas=np.genfromtxt('data.txt', delimiter=',' , skipheader=1)

TypeError: genfromtxt() got an unexpected keyword argument 'skipheader'

In [28]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f53482ddba8>)

In [35]:
deita_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [36]:
deita_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [40]:
deita_data.shape

(10000, 3)

In [43]:
finali=deita_data @ weights

In [44]:
finali

array([12729., 10356., 10455., ..., 11304., 13363., 11164.])

In [45]:
finali.shape

(10000,)

In [50]:
finali_results = np.concatenate((deita_data, finali.reshape(10000, 1)), axis=1)

In [51]:
finali_results

array([[   25.,    76.,    99., 12729.],
       [   39.,    65.,    70., 10356.],
       [   59.,    45.,    77., 10455.],
       ...,
       [   99.,    62.,    58., 11304.],
       [   70.,    71.,    91., 13363.],
       [   92.,    39.,    76., 11164.]])

In [55]:
np.savetxt('finali_results.txt', 
           finali_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')